---
    environment: production
    chdir: /webapp/binaryattraction
    address: 127.0.0.1
    user: webapp
    group: webapp
    port: 12501
    pid: /webapp/binaryattraction/log/sinatra.pid
    rackup: /webapp/binaryattraction/config.ru
    log: /webapp/binaryattraction/sinatra.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true
